# Project information
site_name: Cloud Pak for Data Health Care Workshop
site_url: https://ibm.github.io/cpd-workshop-health-care
site_author: IBM Developer

# Repository
repo_name: cpd-workshop-health-care
repo_url: https://github.com/ibm/cpd-workshop-health-care
edit_uri: edit/master/workshop
docs_dir: workshop

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md
  - Workshop:
    - Pre-work: pre-work/README.md
    - Data Connetion and Virtualization: data-connection-and-virtualization/README.md
    - Data Visualization with Data Refinery: data-visualization-and-refinery/README.md
    - Enterprise data governance for Admins using Watson Knowledge Catalog: watson-knowledge-catalog-admin/README.md
    - Machine Learning with AutoAI: machine-learning-autoai/README.md
    - Monitoring models with OpenScale GUI (Auto setup Monitoring): openscale-fastpath/README.md
  - Workshop Resources:
    - Additional Resources: resources/README.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2021 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
